# Site settings
title: Mini Project
#email: 
description: > # this means to ignore newlines until "baseurl:"
    Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://panchdevs.github.io/" # the base hostname & protocol for your site
#twitter_username: 
github_username:  panchdevs

# Build settings
markdown: kramdown
